name: Deploy mdBook to External Repo

on:
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout app repo
      uses: actions/checkout@v3

    - name: Install mdBook
      run: |
        curl -sSL https://api.github.com/repos/rust-lang/mdBook/releases/latest \
        | grep "browser_download_url.*unknown-linux-gnu.tar.gz" \
        | cut -d '"' -f 4 \
        | xargs curl -sL \
        | tar xz
        sudo mv mdbook /usr/local/bin

    - name: Build the book
      run: mdbook build docs

    - name: Deploy to docs repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git clone --depth=1 https://x-access-token:${GITHUB_TOKEN}@github.com/nedden/docs.git target-docs
        rm -rf target-docs/*
        cp -r docs/book/* target-docs/

        cd target-docs
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update from app/docs"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}